apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kf-autobot
resources:
- deployment.yaml
images:
- digest: sha256:ec4d1ea45b47ce34c14f6c023d40d562ff26db5ae874af6947a17a6199520ad6
  name: groups
  newName: gcr.io/kf-infra-gitops/groups-sync:f933775
